### ISSUE TITLE
请教一下端到端测试的时候，multi-scale test的配置

### ISSUE THREAD

**Issue by kkoo1** [Wei-ucas/TPSNet#10]
作者您好，我看您论文中端到端使用了multi-scale test，请问是如何配置的呢？github中给出的权重，我在totaltext数据集上复现是76.5这是已经使用multi-scale test后的嘛？能否请教一下multi-scale test如何设置的呢？

**Comment by kkoo1** [comment]
尊敬的作者您好，您的TPSNet工作很有意义对我有很大的启发，十分感谢您！但是我最近在复现您TPSNet时遇到如下问题，想向您请教一下。端到端结果复现时，我发现：1、利用您github提供的代码从头开始pretrain之后在totaltext上进行finetune，得到的精度是0.76；2、使用您github上提供的totaltext端到端权重文件，进行test，得到的精度是0.764。两个结果都达不到您论文中端到端模型在totaltext上的78.5，是因为没有使用多尺度测试的原因吗？但是我查看您给的config文件中，发现test_pipeline的type=‘MultiScaleFlipAug’，这是已经使用了多尺度测试吗？还是说您github上给的权重是没有进行多尺度测试的呢？那么多尺度测试应该如何进行设置呢？还望指教，不胜感谢！

**Comment by Wei-ucas** [comment]
您好，感谢关注。test_pipeline的type=‘MultiScaleFlipAug’是不生效的，github上的权重是没有进行多尺度测试的。由于多尺度测试比较耗时，一般仅作为参考并不使用，所以代码中并未配置多尺度测试。如果需要多尺度测试，可以设置多个测试尺度分别预测，然后将输出的结果合并进行nms后处理，得到多尺度融合的结果

**Comment by kkoo1** [comment]
> 您好，感谢关注。test_pipeline的type=‘MultiScaleFlipAug’是不生效的，github上的权重是没有进行多尺度测试的。由于多尺度测试比较耗时，一般仅作为参考并不使用，所以代码中并未配置多尺度测试。如果需要多尺度测试，可以设置多个测试尺度分别预测，然后将输出的结果合并进行nms后处理，得到多尺度融合的结果

作者您好，如何要进行多尺度的话，是直接在test_pipeline的Resize中，img_scale设置多个尺度就行了吗？还需要进行其他改变嘛？能否提供相关代码进行参考呢？谢谢~

**Comment by Wei-ucas** [comment]
开源代码暂不支持一次性预测多个尺度，如果要进行多尺度测试，需要将[img_scale](https://github.com/Wei-ucas/TPSNet/blob/4b06769120e12a84e4a489b0e5dd11ecfa7ba0cf/configs/tpsnet/tpsnet_totaltext.py#L112)分别设置为不同值，分别输出预测结果，每张图在不同尺度下的预测合并进行NMS处理
