### ISSUE TITLE
coeff_maps = np.zeros((2*self.num_fiducial+6, h, w), dtype=np.float32)why？

### ISSUE THREAD

**Issue by jstacer1** [Wei-ucas/TPSNet#11]

**Comment by jstacer1** [comment]
batch_T[y,x,0,:] = batch_T[y,x,0,:] - `yx[:,[1,0]].astype(np.float32)?

**Comment by Wei-ucas** [comment]
您好，能否描述一下您的问题是什么

**Comment by jstacer1** [comment]
> 您好，能否描述一下您的问题是什么
您好，我想请教一下这部分代码的目的以及作用是什么呢，在tpsnet_targets.py中line331~line337中

**Comment by jstacer1** [comment]
> 您好，能否描述一下您的问题是什么
很迷惑这里的y x坐标是怎么改变的呢？

**Comment by Wei-ucas** [comment]
你好，对每一个前景点（文字区域的像素，坐标（x,y)）都有一个tps参数，该TPS参数以对应的(x,y)坐标为原点，从ground truth 轮廓计算出的tps参数（`batch_T[y,x,] `）的原点本来是整个图片的原点，因此需要将其转换到对应的(x,y)坐标点上
