### ISSUE TITLE
请问如何mlt2019和art2019训练并测试

### ISSUE THREAD

**Issue by jstacer1** [Wei-ucas/TPSNet#14]

**Comment by Wei-ucas** [comment]
你好，可以参考ICDAR竞赛网站上的说明https://rrc.cvc.uab.es/?ch=15

**Comment by 256-7421142** [comment]
> 你好，可以参考ICDAR竞赛网站上的说明https://rrc.cvc.uab.es/?ch=15

感谢您的指导，那icdar2015也是只能在官网上面提交测试吗，我尝试用TPSNet在自己的数据集上面训练测试，目前训练集格式应该已经转化好了（因为已经能训练模型），但是测试的时候报错了，没有my_text_results.json，我参考这个代码https://github.com/Wei-ucas/TPSNet/blob/master/mmocr/core/evaluation/evaluation_e2e/create_custom_test.py
，但是不知道如何生成detection result .json 文件，麻烦您可以提供更多的细节吗？

**Comment by 256-7421142** [comment]
您好，我仔细阅读了参考要求，但是还不知道如何基于您的项目，生成对应的检测结果呢



---原始邮件---
发件人: "Wei ***@***.***&gt;
发送时间: 2024年6月18日(周二) 下午2:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Wei-ucas/TPSNet] 请问如何mlt2019和art2019训练并测试 (Issue #14)




 
你好，可以参考ICDAR竞赛网站上的说明https://rrc.cvc.uab.es/?ch=15

**Comment by 256-7421142** [comment]
直接使用mmocr下面的tools/test.py 指定--format-only会错误



---原始邮件---
发件人: "Wei ***@***.***&gt;
发送时间: 2024年6月18日(周二) 下午2:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Wei-ucas/TPSNet] 请问如何mlt2019和art2019训练并测试 (Issue #14)




 
你好，可以参考ICDAR竞赛网站上的说明https://rrc.cvc.uab.es/?ch=15
