### ISSUE TITLE
训练数据集

### ISSUE THREAD

**Issue by jolt2017** [Wei-ucas/TPSNet#2]
1.你好，请问你是如何把原始标注，转换成训练模型时候使用的标注的，哪一部分代码？方便贴下路径么。感谢！

**Comment by Wei-ucas** [comment]
你好，已将相关代码更新在[tools/data/texte2e](https://github.com/Wei-ucas/TPSNet/tree/master/tools/data/texte2e/)，对于totaltext, ctw1500等数据集，可以直接用相关代码从原始标注进行转换，对synthtext-150k的标注，可以使用bezier2polygon_coco.py 进行转换
