### ISSUE TITLE
请问一下大佬，回归分支中self.out_channels_reg = (self.num_fiducial + 3) * 2，是什么意思啊

### ISSUE THREAD

**Issue by wuxiaolianggit** [Wei-ucas/TPSNet#3]
大佬您好，请问一下大佬，回归分支中self.out_channels_reg = (self.num_fiducial + 3) * 2，是什么意思啊 @Wei-ucas

**Comment by Wei-ucas** [comment]
你好，这是设定了回归输出的参数个数，num_fiducial个控制点对应的TPS参数个数为 （num_fiducial+3) * 2

**Comment by wuxiaolianggit** [comment]
多谢大佬的解答，还有一个问题，就是类别的输出，为什么要这样设置呢？
 if self.use_sigmod:
            p = 1
        else:
            p=2
        self.out_channels_cls = 2 * p
大佬可以解答一下吗

**Comment by wuxiaolianggit** [comment]
多谢大佬的解答，还有一个问题，就是类别的输出，为什么要这样设置呢？
if self.use_sigmod:
p = 1
else:
p=2
self.out_channels_cls = 2 * p
大佬可以解答一下吗？ @Wei-ucas

**Comment by Wei-ucas** [comment]
分类分支有两个分类任务，预测是否是文本区域和是否是文本中心区域，使用sigmod激活函数，输出的直接就是正类的概率值，所以每个任务只需要输出一个值即可；如果不使用sigmod，就需要使用softmax将正类和负类的数值转化为概率值，即每个任务上要分别预测正类和负类两个值。我的实现中默认不使用sigmod函数

**Comment by wuxiaolianggit** [comment]
首先很感谢，大佬的回复，我听了您的线上报告，对您的论文很感兴趣，很希望能和您进一步讨论。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ww ***@***.***&gt;
发送时间: 2022年11月7日 19:32
收件人: Wei-ucas/TPSNet ***@***.***&gt;
抄送: wuxiaolianggit ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Wei-ucas/TPSNet] 请问一下大佬，回归分支中self.out_channels_reg = (self.num_fiducial + 3) * 2，是什么意思啊 (Issue #3)





 
分类分支有两个分类任务，预测是否是文本区域和是否是文本中心区域，使用sigmod激活函数，输出的直接就是正类的概率值，所以每个任务只需要输出一个值即可；如果不使用sigmod，就需要使用softmax将正类和负类的数值转化为概率值，即每个任务上要分别预测正类和负类两个值。我的实现中默认不使用sigmod函数
