### ISSUE TITLE
tps的参数不太明白

### ISSUE THREAD

**Issue by mstd-jie** [Wei-ucas/TPSNet#4]
为什么target.py中fiducial_dist用的edge，而后处理跟损失中的tps参数fiducial_dist用的是cross呢，以及tps_size参数也不同。 请问在target设置的标签，与后续学习的不应该对应么，不太明白，请大佬解惑

**Comment by Wei-ucas** [comment]
你好，因为我们的损失函数并不是直接在TPS参数向量上计算的，而是利用ground truth拟合的tps参数还原出一个密集连续的轮廓，再和预测的tps参数还原出来的轮廓计算损失，两个还原过程是独立的，所以ground truth拟合轮廓时用的tps参数和模型预测的tps参数设置可以是不一样的。target中用tps拟合ground truth是用了更大的基准点数量num_fuducial，即更高维的tps向量，是为了更加准确地保留标注的形状，但是模型中为了压缩复杂度，采用的tps控制点数量就更少一些，两者不同并不影响模型的学习

**Comment by mstd-jie** [comment]
> 

感谢大佬的回复，很抱歉，我只明白了损失部分参数设置可以不同，但target中用polygon构建tps参数，和后处理中用tps参数得到polygon，这两部分的fiducial_dist等参数不应该一致么。

**Comment by Wei-ucas** [comment]
后处理时是需要将预测的tps参数还原为polygon，所以后处理的fiducial_dist等参数应该和损失部分即模型的参数相同，这与target中用什么样的参数构建tps参数无关。只要tps参数向量和tps的fiducial_dist、num_fiducial等参数匹配就能还原出正确的polygon

**Comment by mstd-jie** [comment]
> 后处理时是需要将预测的tps参数还原为polygon，所以后处理的fiducial_dist等参数应该和损失部分即模型的参数相同，这与target中用什么样的参数构建tps参数无关。只要tps参数向量和tps的fiducial_dist、num_fiducial等参数匹配就能还原出正确的polygon

我在损失中直接对tps参数进行l1损失计算，发现它的后处理用的fiducial_dist为cross才行，而target中得到的fiducial_disy用的是edge，不明白为什么二者为什么是不同的

**Comment by mstd-jie** [comment]
还是不太明白为什么与target中的fiducial_dist无关，我在target中试了反向得到polygon，用edge才有效，为什么后处理中必须是cross呢 （损失我换成了只针对tps参数的，不涉及cross呀) ，请大佬指点一下

**Comment by mstd-jie** [comment]
而且loss中根据tps参数得到gt_polygon不也应该用edge么，因为target中是用edge得到的tps参数，那它反向得到polygon咋就换成了cross呢

**Comment by Wei-ucas** [comment]
后处理时是将预测的tps向量解码成polygon，因此后处理的fiducial_dist等参数应该和计算损失时将预测的tps向量还原为polygon的参数一致，即[tpsnet_head.py中的73行](https://github.com/Wei-ucas/TPSNet/blob/master/mmocr/models/textend2end/det_heads/tpsnet_head.py#:~:text=self.decoder%20%3D%20TPS(self.num_fiducial%2Cnum_points%3Dnum_reconstr_points%2Cgrid_size%3Dsample_size%2C%20fiducial_dist%3Dfiducial_dist))应该和[tpsnet_losses.py中的第32行](https://github.com/Wei-ucas/TPSNet/blob/master/mmocr/models/textend2end/losses/tpsnet_losses.py#:~:text=self.tps_decoder%20%3D%20TPS(num_fiducial%2C%20num_points%3Dnum_sample%2Cgrid_size%3D(2%2C2)%2C%20fiducial_dist%3Dfiducial_dist))里面的num_fiducial,fiducial_dist参数相同

**Comment by mstd-jie** [comment]
> 后处理时是将预测的tps向量解码成polygon，因此后处理的fiducial_dist等参数应该和计算损失时将预测的tps向量还原为polygon的参数一致，即[tpsnet_head.py中的73行](https://github.com/Wei-ucas/TPSNet/blob/master/mmocr/models/textend2end/det_heads/tpsnet_head.py#:~:text=self.decoder%20%3D%20TPS(self.num_fiducial%2Cnum_points%3Dnum_reconstr_points%2Cgrid_size%3Dsample_size%2C%20fiducial_dist%3Dfiducial_dist))应该和[tpsnet_losses.py中的第32行](https://github.com/Wei-ucas/TPSNet/blob/master/mmocr/models/textend2end/losses/tpsnet_losses.py#:~:text=self.tps_decoder%20%3D%20TPS(num_fiducial%2C%20num_points%3Dnum_sample%2Cgrid_size%3D(2%2C2)%2C%20fiducial_dist%3Dfiducial_dist))里面的num_fiducial,fiducial_dist参数相同

感谢大佬的回复，我大致明白了，能否加下大佬的联系方式呀

**Comment by Wei-ucas** [comment]
可以留下你的邮箱我发给你

**Comment by mstd-jie** [comment]
***@***.***，感谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 下午3:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Wei-ucas/TPSNet] tps的参数不太明白 (Issue #4)




 
可以留下你的邮箱我发给你

**Comment by Wei-ucas** [comment]
邮箱似乎被屏蔽了，我看不到，你可以通过我的论文中的邮件地址和我联系

**Comment by mstd-jie** [comment]
> 

嗯嗯，好的，感谢大佬
