### ISSUE TITLE
TypeError: Caught TypeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by jstacer1** [Wei-ucas/TPSNet#8]
作者你好，当我用1块gpu训练到一个epoch结束时，报错TypeError: Caught TypeError in DataLoader worker process 0.，我检查了totaltext数据集a) Train - It contains 1255 images. b) Test - It contains 300 images，一共1555张图片，为什么训练的时候显示一个epoch会训练1570张图片呢，还有为什么只会在epoch·训练结束时才报错呢

2023-08-17 21:32:36,974 - mmocr - INFO - Epoch [1][1560/1570]   lr: 1.000e-03, eta: 21:28:11, time: 0.490, data_time: 0.023, memory: 7799, loss_text: 1.3758, loss_center: 1.0994, loss_point: 2.7431, loss_ba: 5.6853, loss: 10.9036

**Comment by Wei-ucas** [comment]
你好，为了减少重复创建dataloader导致的时间消耗，采用了[RepeatDataset](https://github.com/Wei-ucas/TPSNet/blob/b40faa8d7329117883d280e7e6ab30f5bef50c85/configs/tpsnet/tpsnet_totaltext_det.py#L118C8-L118C30)，也就是一个epoch会将训练数据重复5次，所以对应的iteration数量为ceil(1255 / 4) x 5. (1560/1570表示iteration进度). 你提到的训练错误我暂未遇到过，你可以检查一下环境配置，或者放上完整的错误信息方便我检查一下原因

**Comment by 256-7421142** [comment]
> 你好，为了减少重复创建dataloader导致的时间消耗，采用了[RepeatDataset](https://github.com/Wei-ucas/TPSNet/blob/b40faa8d7329117883d280e7e6ab30f5bef50c85/configs/tpsnet/tpsnet_totaltext_det.py#L118C8-L118C30)，也就是一个epoch会将训练数据重复5次，所以对应的iteration数量为ceil(1255 / 4) x 5. (1560/1570表示iteration进度). 你提到的训练错误我暂未遇到过，你可以检查一下环境配置，或者放上完整的错误信息方便我检查一下原因
感谢回复，我下载的abcnet作者提供的totaltext百度网盘数据集](https://github.com/aim-uofa/AdelaiDet/blob/master/datasets/README.md)，出现这个报错是否是因为你提供的标注文件和这个不一样，方便发一份totaletext数据集到我的邮箱2567421142@qq.com吗，我google网盘下载的标注文件总是失败。

**Comment by 256-7421142** [comment]
> 你好，为了减少重复创建dataloader导致的时间消耗，采用了[RepeatDataset](https://github.com/Wei-ucas/TPSNet/blob/b40faa8d7329117883d280e7e6ab30f5bef50c85/configs/tpsnet/tpsnet_totaltext_det.py#L118C8-L118C30)，也就是一个epoch会将训练数据重复5次，所以对应的iteration数量为ceil(1255 / 4) x 5. (1560/1570表示iteration进度). 你提到的训练错误我暂未遇到过，你可以检查一下环境配置，或者放上完整的错误信息方便我检查一下原因

感谢作者，这个问题已解决

**Comment by 256-7421142** [comment]
> > 你好，为了减少重复创建dataloader导致的时间消耗，采用了[RepeatDataset](https://github.com/Wei-ucas/TPSNet/blob/b40faa8d7329117883d280e7e6ab30f5bef50c85/configs/tpsnet/tpsnet_totaltext_det.py#L118C8-L118C30)，也就是一个epoch会将训练数据重复5次，所以对应的iteration数量为ceil(1255 / 4) x 5. (1560/1570表示iteration进度). 你提到的训练错误我暂未遇到过，你可以检查一下环境配置，或者放上完整的错误信息方便我检查一下原因



> 你好，为了减少重复创建dataloader导致的时间消耗，采用了[RepeatDataset](https://github.com/Wei-ucas/TPSNet/blob/b40faa8d7329117883d280e7e6ab30f5bef50c85/configs/tpsnet/tpsnet_totaltext_det.py#L118C8-L118C30)，也就是一个epoch会将训练数据重复5次，所以对应的iteration数量为ceil(1255 / 4) x 5. (1560/1570表示iteration进度). 你提到的训练错误我暂未遇到过，你可以检查一下环境配置，或者放上完整的错误信息方便我检查一下原因

作者你好，小白问一下[tpsnet_totaltext_det.py](https://github.com/Wei-ucas/TPSNet/blob/master/configs/tpsnet/tpsnet_totaltext_det.py)在训练的时候是如何使用验证集和测试集的呢

**Comment by Wei-ucas** [comment]
对于totaltext数据集，并未划分单独划分验证集，而是直接在测试集上进行测试，所以验证集与测试集相同
