### ISSUE TITLE
请教训练art2019数据集的config怎么配置

### ISSUE THREAD

**Issue by mstd-jie** [Wei-ucas/TPSNet#9]
作者您好，我想跑一下art2019的数据集，请问怎么配置呢。 ps:之前我跑了您的端到端代码，totaltext的检测f-measure有88.8。所以想试一下更大的数据集

**Comment by Wei-ucas** [comment]
您好，感谢您的关注，ART数据集和total ctw类似，您只需要将标注转化为相同的coco格式即可，其他训练参数可以不变。另外ART测试时需要更大的尺寸才能获得比较最好的效果，您可以适当增大测试尺度尝试。

**Comment by mstd-jie** [comment]
> 您好，感谢您的关注，ART数据集和total ctw类似，您只需要将标注转化为相同的coco格式即可，其他训练参数可以不变。另外ART测试时需要更大的尺寸才能获得比较最好的效果，您可以适当增大测试尺度尝试。

嗯嗯，请问您测试的尺寸大概是多大呀，我试一下。

**Comment by mstd-jie** [comment]
作者您好，我还有一个问题，就是我想从头开始训练，但是我下载的MLT2017的数据集跟您给的标签不一致。MLT官网数据集只有9000张图，且每张图片的名称跟您提供的也不一致哎

**Comment by Wei-ucas** [comment]
您好，ART测试尺度需要保持短边大于1600（保持长宽比）。感谢您的反馈，这里给出的标签是MLT19的标签（相比MLT17多了1000张图），而且使用的是ABCNet预处理后的数据集（修改了图片命名），请从https://github.com/aim-uofa/AdelaiDet/blob/master/datasets/README.md下载

**Comment by mstd-jie** [comment]
感谢指导，我没问题了

**Comment by 256-7421142** [comment]
> 您好，ART测试尺度需要保持短边大于1600（保持长宽比）。感谢您的反馈，这里给出的标签是MLT19的标签（相比MLT17多了1000张图），而且使用的是ABCNet预处理后的数据集（修改了图片命名），请从[https://github.com/aim-uofa/AdelaiDet/blob/master/datasets/README.md下载](https://github.com/aim-uofa/AdelaiDet/blob/master/datasets/README.md%E4%B8%8B%E8%BD%BD)
这里貌似只有MLT19训练集的图片和标签，请问如何在MLT2019测试集上面做测试呢

**Comment by 256-7421142** [comment]
> 作者您好，我还有一个问题，就是我想从头开始训练，但是我下载的MLT2017的数据集跟您给的标签不一致。MLT官网数据集只有9000张图，且每张图片的名称跟您提供的也不一致哎



> 作者您好，我还有一个问题，就是我想从头开始训练，但是我下载的MLT2017的数据集跟您给的标签不一致。MLT官网数据集只有9000张图，且每张图片的名称跟您提供的也不一致哎

您好，我也想在mlt2019和art2019训练并测试，请问您方便提供一下config文件吗，而且貌似这两个数据集的test是没有公开的吗，是只能在原比赛官网上面提交测试吗？
